export const CASES_REQUEST = "CASES_REQUEST";
export const CASES_SUCCESS = "CASES_SUCCESS";
export const CASES_FAIL = "CASES_FAIL";

export const CASE_LIST_MY_REQUEST = "CASE_LIST_MY_REQUEST";
export const CASE_LIST_MY_SUCCESS = "CASE_LIST_MY_SUCCESS";
export const CASE_LIST_MY_FAIL = "CASE_LIST_MY_FAIL";

// redux/caseConstants.js
export const CASE_CREATE_REQUEST = "CASE_CREATE_REQUEST";
export const CASE_CREATE_SUCCESS = "CASE_CREATE_SUCCESS";
export const CASE_CREATE_FAIL = "CASE_CREATE_FAIL";

export const CASE_LIST_REQUEST = "CASE_LIST_REQUEST";
export const CASE_LIST_SUCCESS = "CASE_LIST_SUCCESS";
export const CASE_LIST_FAIL = "CASE_LIST_FAIL";

export const CASE_RESET = "CASE_RESET";


// Evolution d’un dossier
export const CASE_EVOLUTION_REQUEST = "CASE_EVOLUTION_REQUEST";
export const CASE_EVOLUTION_SUCCESS = "CASE_EVOLUTION_SUCCESS";
export const CASE_EVOLUTION_FAIL = "CASE_EVOLUTION_FAIL";
export const CASE_EVOLUTION_RESET = "CASE_EVOLUTION_RESET";


 export const CASES_LIST_REQUEST = "CASES_LIST_REQUEST";
export const CASES_LIST_SUCCESS = "CASES_LIST_SUCCESS";
export const CASES_LIST_FAIL = "CASES_LIST_FAIL";


export const CASE_LIST_ALL_REQUEST = "CASE_LIST_ALL_REQUEST";
export const CASE_LIST_ALL_SUCCESS = "CASE_LIST_ALL_SUCCESS";
export const CASE_LIST_ALL_FAIL = "CASE_LIST_ALL_FAIL";



