export const DEPENSE_LIST_REQUEST = "DEPENSE_LIST_REQUEST";
export const DEPENSE_LIST_SUCCESS = "DEPENSE_LIST_SUCCESS";
export const DEPENSE_LIST_FAIL = "DEPENSE_LIST_FAIL";


export const DEPENSE_EDIT_REQUEST = "DEPENSE_EDIT_REQUEST";
export const DEPENSE_EDIT_SUCCESS = "DEPENSE_EDIT_SUCCESS";
export const DEPENSE_EDIT_FAIL = "DEPENSE_EDIT_FAIL";


export const DEPENSE_DELETE_REQUEST = "DEPENSE_DELETE_REQUEST";
export const DEPENSE_DELETE_SUCCESS = "DEPENSE_DELETE_SUCCESS";
export const DEPENSE_DELETE_FAIL = "DEPENSE_DELETE_FAIL";

export const DEPENSE_CREATE_REQUEST = "DEPENSE_CREATE_REQUEST";
export const DEPENSE_CREATE_SUCCESS = "DEPENSE_CREATE_SUCCESS";
export const DEPENSE_CREATE_FAIL = "DEPENSE_CREATE_FAIL";
export const DEPENSE_CREATE_RESET = "DEPENSE_CREATE_RESET";


export const DEPENSE_UPDATE_REQUEST = "DEPENSE_UPDATE_REQUEST";
export const DEPENSE_UPDATE_SUCCESS = "DEPENSE_UPDATE_SUCCESS";
export const DEPENSE_UPDATE_FAIL = "DEPENSE_UPDATE_FAIL";
export const DEPENSE_UPDATE_RESET = "DEPENSE_UPDATE_RESET";
