export const REPORT_CONSULTATION_REQUEST = "REPORT_CONSULTATION_REQUEST";
export const REPORT_CONSULTATION_SUCCESS = "REPORT_CONSULTATION_SUCCESS";
export const REPORT_CONSULTATION_FAIL = "REPORT_CONSULTATION_FAIL";





